gText_Birch_Welcome::
	.string "What Up Dog!\p"
	.string "I heard you are up for a little\n"
    .string "challenge!\p"
	.string "I am PIMP DADDY,\n"
    .string "always ready to please.\p"
	.string "Here is one of my toys.\p"
	.string "$"

gText_Birch_Pokemon::
	.string "Show me some of your moves\n"
    .string "and I may give you your own!\p"
	.string "$"

gText_Birch_MainSpeech::
	.string "That's what I do.\p"
	.string "$"

gText_Birch_AndYouAre::
	.string "And you are?$"

gText_Birch_BoyOrGirl::
	.string "Do you have a penis?\n"
	.string "Or a pussy?$"

gText_Birch_WhatsYourName::
	.string "All right.\n"
	.string "What's your name?$"

gText_Birch_SoItsPlayer::
	.string "So it's, DrieschDrieschson\n"
    .string "aehm I mean {PLAYER}{KUN}?$"

gText_Birch_YourePlayer::
	.string "Ah, okay!\p"
	.string "You're {PLAYER}{KUN} who's moving to my\n"
	.string "hometown of LITTLEROOT.\l"
	.string "I get it now!\p"
	.string "$"

gText_Birch_AreYouReady::
	.string "Come see me in my harem.\p"
	.string "$"
